"""Pydantic data models for analysis pipeline."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class AgentReport(BaseModel):
    """Report generated by an analyst agent."""

    agent_name: str
    display_name: str
    content: str
    data_sources: list[str] = Field(default_factory=list)


class DebateResult(BaseModel):
    """Result of the Bull vs Bear debate."""

    bull_case: AgentReport
    bear_case: AgentReport
    rounds: int = 1


class KeyFact(BaseModel):
    """A single cited fact extracted from data sources."""

    fact: str
    source: str  # e.g. "EDINET FY2024", "TDNET 2026-01-14", "BOJ IR01"


class TradingDecision(BaseModel):
    """Trading decision from the Trader agent."""

    action: Literal["BUY", "SELL", "HOLD"]
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    thesis: str = ""
    watch_conditions: list[str] = Field(default_factory=list)
    key_facts: list[KeyFact] = Field(default_factory=list)
    target_price: float | None = None
    stop_loss: float | None = None
    position_size: Literal["small", "medium", "large"] | None = None


class RiskReview(BaseModel):
    """Risk assessment from the Risk Manager."""

    approved: bool
    concerns: list[str] = Field(default_factory=list)
    max_position_pct: float | None = None
    reasoning: str


class AnalysisResult(BaseModel):
    """Complete analysis result from the full pipeline."""

    code: str
    company_name: str | None = None
    analyst_reports: list[AgentReport] = Field(default_factory=list)
    debate: DebateResult | None = None
    decision: TradingDecision | None = None
    risk_review: RiskReview | None = None
    sources_used: list[str] = Field(default_factory=list)
    model: str = "gpt-4o-mini"
    timestamp: datetime = Field(default_factory=datetime.now)
    raw_data: dict[str, Any] = Field(default_factory=dict)


class PortfolioResult(BaseModel):
    """Result of parallel multi-stock portfolio analysis."""

    codes: list[str]
    results: list[AnalysisResult]
    failed_codes: list[str] = Field(default_factory=list)
    model: str = "gpt-4o-mini"
    timestamp: datetime = Field(default_factory=datetime.now)

    @property
    def buy_results(self) -> list[AnalysisResult]:
        return [r for r in self.results if r.decision and r.decision.action == "BUY"]

    @property
    def sell_results(self) -> list[AnalysisResult]:
        return [r for r in self.results if r.decision and r.decision.action == "SELL"]

    @property
    def hold_results(self) -> list[AnalysisResult]:
        return [r for r in self.results if r.decision and r.decision.action == "HOLD"]
